package chemistry_checker;

import java_cup.runtime.*;
import java.io.InputStreamReader;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Collections;

/**
 * This is a test!
 */

parser code {:
	public static void main(String args[]) throws Exception {
		//new parser(new Yylex(new InputStreamReader(System.in))).parse();
		new parser(new Yylex(new InputStreamReader(new FileInputStream("src/test.txt")))).parse();
	}
:}
action code {:
	public String exprToString(ArrayList<String> expr) {
	    String result = expr.toString();
	    result = result.replace("[", "").replace("]", "").replace(" ,", " + ");
	    return result;
	}

	public String eqnToString(ArrayList<String> l, ArrayList<String> r) {
	    String result = l.toString() + " -> " + r.toString();
	    result = result.replace("[", "").replace("]", "").replace(", ", " + ");
	    return result;
    }
:}

terminal END, PLUS, TO, LPAREN, RPAREN, ELEMENT, CHARGE, STATE;
terminal Integer NUMBER;

non terminal expr_list, expr_part;
non terminal ArrayList<String> expr;
non terminal String group, molecule;

precedence left PLUS;
precedence left TO;

expr_list   ::= expr_list expr_part | expr_part;
expr_part   ::= expr:e                                  {: Collections.sort(e); System.out.println(exprToString(e)); :} END
                | expr:l TO expr:r                      {: Collections.sort(l); Collections.sort(r); System.out.println(eqnToString(l, r)); :} END
                ;
expr        ::=  NUMBER:n molecule:m STATE:s            {: RESULT=new ArrayList<String>(); RESULT.add(n.toString() + ".\\mol{" + m.toString() + "}\\state{" + s.toString() + "}"); :}
                | NUMBER:n molecule:m                   {: RESULT=new ArrayList<String>(); RESULT.add(n.toString() + ".\\mol{" + m.toString() + "}"); :}
                | molecule:m STATE:s                    {: RESULT=new ArrayList<String>(); RESULT.add("\\mol{" + m.toString() + "}\\state{" + s.toString() + "}"); :}
                | molecule:m                            {: RESULT=new ArrayList<String>(); RESULT.add("\\mol{" + m.toString() + "}"); :}
                | expr:l PLUS expr:r                    {: RESULT=new ArrayList<String>(); RESULT.addAll(l); RESULT.addAll(r); :}
                | error PLUS expr:e                     {: RESULT=new ArrayList<String>(); RESULT.add("\\error"); RESULT.addAll(e); :}
                | error                                 {: RESULT=new ArrayList<String>(); RESULT.add("\\error"); :}
                ;
group       ::= ELEMENT:e                               {: RESULT=new String(e.toString()); :}
                | ELEMENT:e NUMBER:n                    {: RESULT=new String(e.toString() + "_{" + n.toString() + "}"); :}
                | group:g CHARGE:c                      {: RESULT=new String(g.toString() + c.toString()); :}
                | LPAREN molecule:m RPAREN NUMBER:n     {: RESULT=new String("(" + m.toString() + ")" + "_{" + n.toString() + "}"); :}
                ;
molecule    ::= group:g                                 {: RESULT=new String(g.toString()); :}
                | group:g molecule:m                    {: RESULT=new String(g.toString() + "." + m.toString()); :}
                ;

